# Generated by Django 4.0.4 on 2022-05-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='x_coord',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='y_coord',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
    ]
