# Generated by Django 4.0.4 on 2022-05-22 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_rename_sender_message_sender_is_chat_user1_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('x_coord', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('y_coord', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile1', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile2', to='api.profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
